name: Build, Bump, and Release

on:
  push:
    branches: ["master"]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ensures full history for tag operations

      - name: Bump version and tag
        uses: renderbox/github-actions/bump-version@main
        with:
          version-part: patch
          python-version: '3.12'

      - name: Build Python Package
        if: success()  # only run if bump succeeded
        uses: renderbox/github-actions/build-python-package@main
        with:
          python-version: '3.12'

      - name: Publish to PyPI
        if: success()  # only run if build succeeded
        uses: renderbox/github-actions/publish-to-pypi@main
